"""
Report Generator
Assembles all agent outputs into a structured institutional research report.
Produces Markdown output formatted like Goldman Sachs / Morgan Stanley equity research.
"""

from __future__ import annotations
import os
import json
from datetime import datetime
from typing import Any


REPORT_HEADER = """
╔══════════════════════════════════════════════════════════════════════════════════╗
║                    EQUITY RESEARCH — INSTITUTIONAL GRADE                       ║
║                    AI-Native Research Operating System                         ║
╚══════════════════════════════════════════════════════════════════════════════════╝
"""

DISCLAIMER = """
---
*This report is generated by an AI research system for informational and analytical
purposes only. It does not constitute investment advice. All projections, price targets,
and ratings are illustrative. Past performance is not indicative of future results.
Verify all data independently before making investment decisions.*

---
"""


def _format_price(val) -> str:
    if val is None:
        return "N/A"
    try:
        return f"${float(val):,.2f}"
    except (TypeError, ValueError):
        return str(val)


def _format_large(val) -> str:
    if val is None:
        return "N/A"
    try:
        v = float(val)
        if abs(v) >= 1e12:
            return f"${v/1e12:.2f}T"
        if abs(v) >= 1e9:
            return f"${v/1e9:.2f}B"
        if abs(v) >= 1e6:
            return f"${v/1e6:.2f}M"
        return f"${v:,.0f}"
    except (TypeError, ValueError):
        return str(val)


def _format_pct(val) -> str:
    if val is None:
        return "N/A"
    try:
        return f"{float(val)*100:.1f}%"
    except (TypeError, ValueError):
        return str(val)


class ReportGenerator:
    """
    Assembles all agent outputs into a structured research report.
    """

    def __init__(self, ticker: str, company_name: str, domain: str, rating: str = ""):
        self.ticker = ticker.upper()
        self.company_name = company_name
        self.domain = domain
        self.rating = rating
        self.generated_at = datetime.now()
        self.sections: list[str] = []

    def _section(self, title: str, content: str) -> str:
        bar = "═" * 80
        return f"\n{bar}\n## {title}\n{bar}\n\n{content}\n"

    def _subsection(self, title: str, content: str) -> str:
        return f"\n### {title}\n\n{content}\n"

    def build_cover_page(self, market_data: dict, pm_output: dict) -> str:
        fundamentals = market_data.get("fundamentals", {})
        price_hist = market_data.get("price_history", {})
        analyst_rec = market_data.get("analyst_recommendations", {})
        pm_decision = pm_output.get("investment_decision", "")
        exec_summary = pm_output.get("executive_summary", "")

        # Extract rating from PM decision
        rating_line = ""
        for line in pm_decision.split("\n"):
            if "RATING" in line.upper() or "BUY" in line or "HOLD" in line or "SELL" in line:
                rating_line = line.strip()
                break

        total_buy = analyst_rec.get("strongBuy", 0) + analyst_rec.get("buy", 0)
        total_hold = analyst_rec.get("hold", 0)
        total_sell = analyst_rec.get("sell", 0) + analyst_rec.get("strongSell", 0)

        cover = f"""
{REPORT_HEADER}

# {self.company_name} ({self.ticker})
## Sector: {self.domain}
### Report Date: {self.generated_at.strftime('%B %d, %Y')}

---

| Metric | Value |
|--------|-------|
| Market Cap | {_format_large(fundamentals.get('marketCap'))} |
| Enterprise Value | {_format_large(fundamentals.get('enterpriseValue'))} |
| 52-Week Range | {_format_price(price_hist.get('52w_low'))} – {_format_price(price_hist.get('52w_high'))} |
| 1-Year Performance | {price_hist.get('price_change_pct', 'N/A')}% |
| EV/Revenue (TTM) | {fundamentals.get('enterpriseToRevenue', 'N/A')}x |
| EV/EBITDA (TTM) | {fundamentals.get('enterpriseToEbitda', 'N/A')}x |
| P/E (Forward) | {fundamentals.get('forwardPE', 'N/A')}x |
| Revenue Growth (YoY) | {_format_pct(fundamentals.get('revenueGrowth'))} |
| Gross Margin | {_format_pct(fundamentals.get('profitMargins'))} |
| Free Cash Flow | {_format_large(fundamentals.get('freeCashflow'))} |
| Beta | {fundamentals.get('beta', 'N/A')} |

**Street Consensus:** Buy: {total_buy} | Hold: {total_hold} | Sell: {total_sell}

---

**OUR RATING:** {rating_line if rating_line else self.rating}

---

## EXECUTIVE SUMMARY

{exec_summary}

{DISCLAIMER}
"""
        return cover

    def build_full_report(self, all_outputs: dict) -> str:
        """
        Assembles all agent outputs into a structured report.
        all_outputs = {
            'data_collection': {...},
            'sec_filing': {...},
            'earnings_call': {...},
            'industry_research': {...},
            'financial_modeling': {...},
            'valuation': {...},
            'competitive_intelligence': {...},
            'risk_assessment': {...},
            'skeptical_analyst': {...},
            'portfolio_manager': {...},
        }
        """
        md = []

        # --- Cover ---
        market_data = all_outputs.get("data_collection", {})
        pm_out = all_outputs.get("portfolio_manager", {})
        md.append(self.build_cover_page(market_data, pm_out))

        # --- Investment Thesis ---
        pm_decision = pm_out.get("investment_decision", "")
        md.append(self._section("INVESTMENT THESIS & PM DECISION", pm_decision))

        # --- Industry Overview ---
        industry = all_outputs.get("industry_research", {})
        md.append(self._section(
            "INDUSTRY OVERVIEW",
            industry.get("tam_and_trends", "Not generated."),
        ))
        if industry.get("supply_chain_map"):
            md.append(self._subsection("Supply Chain Dependency Map", industry["supply_chain_map"]))
        if industry.get("biotech_analysis"):
            md.append(self._subsection("Biotech Pipeline Analysis", industry["biotech_analysis"]))

        # --- Company Overview / SEC Filings ---
        sec = all_outputs.get("sec_filing", {})
        md.append(self._section(
            "COMPANY OVERVIEW & SEC FILING ANALYSIS",
            sec.get("analysis", "Not generated."),
        ))

        # --- Earnings Call Intelligence ---
        earnings = all_outputs.get("earnings_call", {})
        md.append(self._section(
            "EARNINGS CALL INTELLIGENCE",
            earnings.get("earnings_analysis", "Not generated."),
        ))
        md.append(self._subsection(
            "Management Credibility Assessment",
            earnings.get("management_credibility", ""),
        ))

        # --- Financial Analysis ---
        fin = all_outputs.get("financial_modeling", {})
        md.append(self._section(
            "FINANCIAL ANALYSIS",
            fin.get("revenue_model", "Not generated."),
        ))
        md.append(self._subsection("Margin Trajectory", fin.get("margin_analysis", "")))

        # --- Valuation ---
        val = all_outputs.get("valuation", {})
        md.append(self._section("VALUATION", val.get("dcf_analysis", "Not generated.")))
        md.append(self._subsection("Comparable Company Analysis", val.get("comps_analysis", "")))
        md.append(self._subsection("Price Target Summary", val.get("price_targets", "")))

        # --- Competitive Positioning ---
        comp = all_outputs.get("competitive_intelligence", {})
        md.append(self._section(
            "COMPETITIVE POSITIONING",
            comp.get("competitive_landscape", "Not generated."),
        ))
        md.append(self._subsection("Moat Analysis", comp.get("moat_analysis", "")))
        md.append(self._subsection("Disruption Risk", comp.get("disruption_risks", "")))

        # --- Risk Assessment ---
        risk = all_outputs.get("risk_assessment", {})
        md.append(self._section("RISK ASSESSMENT", risk.get("primary_risks", "Not generated.")))
        md.append(self._subsection("Non-Consensus Tail Risks", risk.get("tail_risks", "")))
        md.append(self._subsection("Risk/Reward Summary", risk.get("risk_reward_summary", "")))

        # --- Skeptical Analyst ---
        skeptic = all_outputs.get("skeptical_analyst", {})
        md.append(self._section("THESIS ATTACK — SKEPTICAL ANALYST", skeptic.get("thesis_attack", "Not generated.")))
        md.append(self._subsection("Bear Case Construction", skeptic.get("bear_case", "")))
        md.append(self._subsection("Variant Perception", skeptic.get("variant_perception", "")))

        # --- Footer ---
        md.append(f"\n---\n*Report generated: {self.generated_at.isoformat()}*\n")

        return "\n".join(md)

    def save(self, report_text: str, output_dir: str) -> str:
        """Save report to disk. Returns file path."""
        os.makedirs(output_dir, exist_ok=True)
        timestamp = self.generated_at.strftime("%Y%m%d_%H%M%S")
        filename = f"{self.ticker}_research_{timestamp}.md"
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_text)
        return filepath
